### ISSUE TITLE
Browser?

### ISSUE THREAD

**Issue by ghost** [myfreeweb/capsicumizer#4]
This looks really cool. Could this work for say firefox or surf? Or wouldn't capsicum deny new sockets?

Does it prevent anything like keyboard capture or screen watching with X? I imagine not.

I guess if network access is limited, then X capture doesn't matter unless say a hacked application spun up a terminal and typed out some netcat command to send screenshots or the like.

**Comment by valpackett** [comment]
Browsers are too complex for this and are designed to handle sandboxing themselves (e.g. content processes are sandboxed, but the network process isn't, to allow spawning sockets). [I have implemented Capsicum support in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1607980)! Writing from a sandboxed Firefox right now.

> Does it prevent anything like keyboard capture or screen watching with X? I imagine not.

Wayland does not provide keyboard capture or screen watching to clients :)

**Comment by ghost** [comment]
That's awesome, thank you! I hope that gets merged.

It sounds like Wayland on FreeBSD is kind of a do-it-yourself thing, right? The FreeBSD Wiki doesn't have a whole lot of information on it. Do you have any tips on using Wayland in FreeBSD? I've used X forever but have no idea where to begin with Wayland.

**Comment by valpackett** [comment]
Wayfire/Sway/Hikari should pretty much just work now even on -STABLE I think (setting `sysctl kern.evdev.rcpt_mask=12` is about the only not-default-yet thing, for proper touchpad support)

I have an info page with all the things: https://unrelenting.technology/kb/FreeBSDDesktop

I'm also working on a "distribution" with everything preconfigured..

**Comment by ghost** [comment]
Very cool, thank you! I'll probably give it a try if it comes out in 12.2. In the meanwhile I'm looking into options to carefully sandbox X applications and prevent X misuse.
